## ຄະນະ: ວິທະຍາສາດທຳມະຊາດ
## ສາຂາ: ວິທະຍາສາດຄອມພິວເຕີ(Computer Science)

 # Porject: Mask Detection

In [11]:
import cv2
import tensorflow
import keras
from PIL import Image

ອ່ານ File ທີ່ໃຊ້ໃນການຈັບໃບໜ້າ

In [12]:
face_cascade = 'haarcascade_frontalface_default.xml'

ທຳການເປີດກ້ອງທີ່ຕິດກັບຄວມພິວເຕີທີ່ເກັບໄວ້ໃນຕົວແປ webcam

In [13]:
webcam = cv2.VideoCapture(0)

ຄຳສັ່ງ read() ເປັນຄຳສັ່ງທີ່ໃຊ້ອ່ານພາບຈາກ webcam ແຕ່ຂໍ້ມູນທີ່ໄດ້ຈາກ webcam ແມ່ນຂໍ້ມູນປະເພດ BGR

In [5]:
success, image_bgr = webcam.read()

ການສົ່ງຂໍ້ມູນຮູບພາບ ຫຼາຍໆຮູບພາບຕິດຕໍ່ກັນ ພວກເຮົາຕ້ອງໃຊ້ while loop ເພື່ອສົ່ງຄຳສັ່ງຂອງພາບຈາກ webcam ເພື່ອສະແດງເປັນວິດີໂອ

In [14]:
while True:
    success, image_bgr = webcam.read()
    if success:
        
        image_bw = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)
        
        face_classifier = cv2.CascadeClassifier(face_cascade)
        faces = face_classifier.detectMultiScale(image_bw)
        print(f'There are {len(faces)} faces found.')
        for face in faces:
            x, y, w, h = face
            cv2.rectangle(image_bgr, (x, y), (x+w, y+h), (0,255,0), 2)
        cv2.imshow("Face Detection", image_bgr)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break
webcam.release()
cv2.destroyAllWindows()

There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 2 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 0 faces found.
There are 0 faces found.
There are 0 faces found.
There are 0 faces found.
There are 0 faces found.
There are 0 faces found.
There are 0 faces found.
There are 0 faces found.
There are 0 faces found.
There are 0 faces found.
There are 0 faces found.
There are 0 faces found.
There are 1 faces found.
There are 2 faces found.
There are 1 faces found.
There are 2 faces found.
There are 2 faces found.
There are 3 faces found.
There are 2 faces found.
There are 2 faces found.
There are 3 faces found.
There are 3 faces found.
There are 2 faces found.
There are 2 faces found.


ສ້າງຂໍ້ມູບຂອງຄົນທີ່ໃສ່ Mask ແລະ ບໍ່ໃສ່ mask ເພື່ອນຳໄປ train model

In [9]:
count = 0
while True:
    success, image_bgr = webcam.read()
    if success:
        image_org = image_bgr.copy()
        image_bw = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)
        
        face_classifier = cv2.CascadeClassifier(face_cascade)
        faces = face_classifier.detectMultiScale(image_bw)
        print(f'There are {len(faces)} faces found.')
        for face in faces:
            x, y, w, h = face
            cv2.rectangle(image_bgr, (x, y), (x+w, y+h), (0,255,0), 2)
            cv2.imwrite(f'mask/mask_{count}.jpg', image_org[y:y+h, x:x+w])
            count+=1
        cv2.imshow("Face Detection", image_bgr)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break
webcam.release()
cv2.destroyAllWindows()

There are 1 faces found.
There are 1 faces found.
There are 2 faces found.
There are 1 faces found.
There are 2 faces found.
There are 0 faces found.
There are 1 faces found.
There are 2 faces found.
There are 1 faces found.
There are 2 faces found.
There are 1 faces found.
There are 0 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 0 faces found.
There are 0 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 2 faces found.
There are 0 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 3 faces found.
There are 2 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.
There are 1 faces found.


### ສ້າງ Classification Model

Teachable Machine ທີ່ຈະຮັບຮູບພາບເພື່ອໃຫ້ Model ລະບຸພາບທີ່ຕ້ອງການໄດ້ ເພື່ອແບ່ງປະເພດພາບທີ່ເຫັນອອກເປັນປະເພດຕ່າງໆ ເຊັ່ນ:ຄົນໃສ່ mask ແລະ ຄົນບໍ່ໃສ່Mask
ເຊິ່ງຈະແບ່ງຂໍ້ມູນອອກເປັນຈັກປະເພດກໍໄດ້ ເຊິ່ງເອີ້ນວ່າ Class ເຮົາຈະເອົານຳພາບຂອງແຕ່ລະClass ເຂົ້າໄປໃຫ້ Machine Learning ຮຽນຮູ້ ແລະ ດາວໂຫລດໂປຣແກຣມທີ່ Ture ສຳເລັດແລ້ວມາໃຊ້ງານສ່ອນໜື່ງຂອງໂຄດຂອງເຮົາ

### ສ້າງ Model ດ້ອຍໂປຣແກຣມສຳເລັດຮູບ

https://teachablemachine.withgoogle.com/train/image

### ຮູບແບບການ Train model

![](M.jpg)

### ທຳຄວາມເຂົ້າໃຈ Medel ເບື້ອງຕົ້ນ

In [9]:
from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

# Load the model
model = load_model('keras_model.h5')

# Create the array of the right shape to feed into the keras model
# The 'length' or number of images you can put into the array is
# determined by the first position in the shape tuple, in this case 1.
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
# Replace this with the path to your image
image = Image.open('mask_3.jpg')
#resize the image to a 224x224 with the same strategy as in TM2:
#resizing the image to be at least 224x224 and then cropping from the center
size = (224, 224)
image = ImageOps.fit(image, size, Image.ANTIALIAS)
 
#turn the image into a numpy array
image_array = np.asarray(image)
# Normalize the image
normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
# Load the image into the array
data[0] = normalized_image_array

# run the inference
prediction = model.predict(data)
print(prediction)


[[5.6668014e-05 9.9994338e-01]]


### ນຳເອົາ Model ມາປະກອບກັບ webcam ແລະ Face Detection

 ຂໍ້ມູນທີ່ຈາກ webcam ເປັນຂໍ້ມູນປະເພດ object array ເຊີ່ງຈະຕ້ອງແປງເປັນ Image object ໃນຮູບແບບຂອງ object ທີ່ໄດ້ຈາກການເປີດໄຟສຈາກຮູບ ແລະ ຕ້ອງແປງສີຈາກສີ BGR ເປັນ RGB
 ຫຼັງຈາກທີ່ເຮົາແປງຂໍ້ມູນຂອງ Webcame ແລະປັບໃຫ້ເຂົ້າກັບຂໍ້ມູນທີ່ໃຊ້ຮ່ວມກັບ Model ທີ່ Train ມາແລ້ວ ເຮົາຈະລວມຄຳສັ່ງເຂົ້າກັນ ແລະ ສະແດງຜົນເປັນ real-time

In [1]:
import cv2
import tensorflow
from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

webcam = cv2.VideoCapture(0)
face_cascade = 'haarcascade_frontalface_default.xml'
face_classifier = cv2.CascadeClassifier(face_cascade)
model = load_model('keras_model.h5')
size = (224, 224)
while True:
    success, image_bgr = webcam.read()
    if success:
        
        image_bw = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)
        image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
        
        faces = face_classifier.detectMultiScale(image_bw)
        for face in faces:
            x, y, w, h = face
            cface_rgb = Image.fromarray(image_rgb[y:y+h,x:x+w])
        
            data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

            image = cface_rgb

            image = ImageOps.fit(image, size, Image.ANTIALIAS)

            image_array = np.asarray(image)

            normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1

            data[0] = normalized_image_array

            prediction = model.predict(data)
            print(prediction)
            if prediction[0][0] < prediction[0][1]:
                cv2.putText(image_bgr, 'MASKED', (x, y-7), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0),2)
                cv2.rectangle(image_bgr, (x, y), (x+w, y+h), (0,255,0), 2)
            else:
                cv2.putText(image_bgr, 'NON_MASKED', (x, y-7), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255),2)
                cv2.rectangle(image_bgr, (x, y), (x+w, y+h), (0,0,255), 2)
        cv2.imshow("Mask Detection", image_bgr)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break
webcam.release()
cv2.destroyAllWindows()

[[9.9980611e-01 1.9396777e-04]]
[[9.9989915e-01 1.0079374e-04]]
[[9.9979621e-01 2.0379429e-04]]
[[9.9982917e-01 1.7080648e-04]]
[[9.9979848e-01 2.0156843e-04]]
[[9.9983311e-01 1.6686982e-04]]
[[9.996933e-01 3.067062e-04]]
[[9.9989212e-01 1.0784482e-04]]
[[9.9987197e-01 1.2802759e-04]]
[[9.9983633e-01 1.6364576e-04]]
[[9.998010e-01 1.990324e-04]]
[[9.9988258e-01 1.1745393e-04]]
[[9.9983299e-01 1.6695641e-04]]
[[9.9978477e-01 2.1529976e-04]]
[[9.998355e-01 1.644954e-04]]
[[9.9987805e-01 1.2193937e-04]]
[[9.9991465e-01 8.5317202e-05]]
[[9.9982554e-01 1.7443801e-04]]
[[9.9987090e-01 1.2912133e-04]]
[[9.9984121e-01 1.5878376e-04]]
[[9.9979633e-01 2.0366142e-04]]
[[9.9985480e-01 1.4516478e-04]]
[[9.9978417e-01 2.1583866e-04]]
[[9.9987388e-01 1.2612545e-04]]
[[9.9973935e-01 2.6064055e-04]]
[[9.9945194e-01 5.4803083e-04]]
[[9.9987555e-01 1.2444351e-04]]
[[9.9981004e-01 1.8994531e-04]]
[[9.9981767e-01 1.8237341e-04]]
[[9.997117e-01 2.882465e-04]]
[[9.9985063e-01 1.4929289e-04]]
[[0.3480766  0.6